### ISSUE TITLE
Actions are not working in production (Nuxt w/ TypeScript)

### ISSUE THREAD

**Issue by domi91c** [michaelolof/vuex-class-component#44]
I'm currently using vuex-class-component in a simple Nuxt Typescript project.  Everything works fine in development, but when I run `npm run build; npm run start` and try to call an action, nothing happens. No functionality or errors.

I'll try to find some time to setup an example repo.

**Comment by SaphuA** [comment]
This is probably related to the namespaces in combination with minification issue as discussed here: https://github.com/michaelolof/vuex-class-component/issues/43

**Comment by domi91c** [comment]
Will that workaround work in 2.0.4? I get the following error when I try to use the @Module decorator:
`$store.getters[(namespacedPath + ("__" + className + "_internal_getter__"))] is not a function`

**Comment by SaphuA** [comment]
Yes that should still work. Can you provide a repro?

**Comment by domi91c** [comment]
I'm not sure what I was doing wrong yesterday, but I made another repo and added 
`@Module({namespacedPath: 'auth'})` to the top of one of my modules and it's working now.

Thank you so much, was not looking forward to rewriting everything in plain Vuex.

**Comment by danielroe** [comment]
This is the same issue as #42, which I've just closed in favour of #43 as I think that is a better description of the underlying cause.

**Comment by michaelolof** [comment]
Duplicate of #43
